### PR TITLE
fix bug in predicting with KNN models for :brutetree algorithm and metric.

### LINKED ISSUE #45: predict errors for `KNNRegressor` when `algorithm = :brutetree` .
A user on julia discourse, recently reported that the code below fails during the prediction phase.
```julia
using DataFrames
using MLJ

X_rand = rand(50,3)
coef = [1; 0; 1]
y_rand = X_rand*coef + rand(50,1)

#convert to dataframe for MLJ inputs
X_rand_df = DataFrames.DataFrame(X_rand, :auto)
y_rand_df = DataFrames.DataFrame(y_rand, :auto)

train_idx, test_idx = partition(eachindex(y_rand_df[:,1]), 0.7, shuffle=true)

Tree = @load KNNRegressor
tree =Tree(algorithm=:brutetree)

mach = machine(tree,  X_rand_df[train_idx, :], y_rand_df[train_idx, 1])

MLJ.fit!(mach)

MLJ.predict(mach, X_rand_df[test_idx,:])
```

### LINKED ISSUE #46: KNN model predict same outcomes irrespective of set metric.
Take for example a `KNNRegressor` model in the following code.
```julia
julia> using MLJ, NearestNeighborModels, DataFrames

julia> X_rand = rand(50,3);

julia> coef = [1; 0; 1];

julia> y_rand = X_rand*coef + rand(50,1);

julia> X_rand_df = DataFrames.DataFrame(X_rand, :auto) #convert to dataframe for MLJ inputs

julia> y_rand_df = DataFrames.DataFrame(y_rand, :auto);

julia> train_idx, test_idx = partition(eachindex(y_rand_df[:,1]), 0.7, shuffle=true);

julia> tree1 = KNNRegressor(algorithm=:brutetree, metric= Euclidean(), reorder = false, leafsize=0)
KNNRegressor(
    K = 5,
    algorithm = :brutetree,
    metric = Euclidean(0.0),
    leafsize = 0,
    reorder = false,
    weights = Uniform())

julia> tree2 = KNNRegressor(algorithm=:brutetree, metric= Cityblock(), reorder = false, leafsize=0)
KNNRegressor(
    K = 5,
    algorithm = :brutetree,
    metric = Cityblock(),
    leafsize = 0,
    reorder = false,
    weights = Uniform())

julia> mach1 = machine(tree1,  X_rand_df[train_idx, :], y_rand_df[train_idx, 1]);

julia> mach2 = machine(tree2,  X_rand_df[train_idx, :], y_rand_df[train_idx, 1]);

julia> fit!(mach1)
[ Info: Training Machine{KNNRegressor,…}.
Machine{KNNRegressor,…} trained 1 time; caches data
  model: KNNRegressor
  args:
    1:  Source @118 ⏎ `Table{AbstractVector{Continuous}}`
    2:  Source @156 ⏎ `AbstractVector{Continuous}`


julia> fit!(mach2)
[ Info: Training Machine{KNNRegressor,…}.
Machine{KNNRegressor,…} trained 1 time; caches data
  model: KNNRegressor
  args:
    1:  Source @759 ⏎ `Table{AbstractVector{Continuous}}`
    2:  Source @962 ⏎ `AbstractVector{Continuous}`

julia> preds1 = MLJ.predict(mach1, X_rand_df[test_idx,:]);

julia> preds2 = MLJ.predict(mach2, X_rand_df[test_idx,:]);

julia> preds1 == preds2
true
```
This returns exactly the same predictions for different metrics. This shouldn't be the case.

### PR DESCRIPTION
**Pull request by OkonSamuel**
```julia
julia> using MLJ, NearestNeighborModels, DataFrames

julia> X_rand = rand(50,3);

julia> coef = [1; 0; 1];

julia> y_rand = X_rand*coef + rand(50,1);

julia> X_rand_df = DataFrames.DataFrame(X_rand, :auto) #convert to dataframe for MLJ inputs

julia> y_rand_df = DataFrames.DataFrame(y_rand, :auto);

julia> train_idx, test_idx = partition(eachindex(y_rand_df[:,1]), 0.7, shuffle=true);

julia> tree1 = KNNRegressor(algorithm=:brutetree, metric= Euclidean(), reorder = false, leafsize=0)
KNNRegressor(
    K = 5,
    algorithm = :brutetree,
    metric = Euclidean(0.0),
    leafsize = 0,
    reorder = false,
    weights = Uniform())

julia> tree2 = KNNRegressor(algorithm=:brutetree, metric= Cityblock(), reorder = false, leafsize=0)
KNNRegressor(
    K = 5,
    algorithm = :brutetree,
    metric = Cityblock(),
    leafsize = 0,
    reorder = false,
    weights = Uniform())

julia> tree3 = KNNRegressor(algorithm=:brutetree)
KNNRegressor(
    K = 5,
    algorithm = :brutetree,
    metric = Euclidean(0.0),
    leafsize = 0,
    reorder = false,
    weights = Uniform())

julia> mach1 = machine(tree1,  X_rand_df[train_idx, :], y_rand_df[train_idx, 1]);

julia> mach2 = machine(tree2,  X_rand_df[train_idx, :], y_rand_df[train_idx, 1]);

julia> mach3 = machine(tree3,  X_rand_df[train_idx, :], y_rand_df[train_idx, 1]);

julia> fit!(mach1)
[ Info: Training Machine{KNNRegressor,…}.
Machine{KNNRegressor,…} trained 1 time; caches data
  model: KNNRegressor
  args:
    1:  Source @344 ⏎ `Table{AbstractVector{Continuous}}`
    2:  Source @234 ⏎ `AbstractVector{Continuous}`


julia> fit!(mach2)
[ Info: Training Machine{KNNRegressor,…}.
Machine{KNNRegressor,…} trained 1 time; caches data
  model: KNNRegressor
  args:
    1:  Source @582 ⏎ `Table{AbstractVector{Continuous}}`
    2:  Source @640 ⏎ `AbstractVector{Continuous}`

julia> fit!(mach3)
[ Info: Training Machine{KNNRegressor,…}.
Machine{KNNRegressor,…} trained 1 time; caches data
  model: KNNRegressor
  args:
    1:  Source @492 ⏎ `Table{AbstractVector{Continuous}}`
    2:  Source @836 ⏎ `AbstractVector{Continuous}`

julia> preds1 = MLJ.predict(mach1, X_rand_df[test_idx,:]);

julia> preds2 = MLJ.predict(mach2, X_rand_df[test_idx,:]);

julia> preds1 == preds2
false

julia> preds3 = MLJ.predict(mach3, X_rand_df[test_idx,:])
15-element Vector{Float64}:
 1.7029412653743503
 1.4591779632945534
 1.582290743528469
 2.101230332732603
 2.2316740656510454
 1.4370807503964989
 1.70609816653188
 1.5000572634358513
 1.6903333540586924
 1.5000572634358516
 1.5193869250110221
 1.0055116437574894
 1.1873231287446022
 1.3289743625868122
 1.1843582933771475
```
closes #46, closes #45.

### CODE REVIEW

**Comment by ablaom** [comment]
Thanks for this!

I will try to review in the next 24 hours.

File: src/NearestNeighborModels.jl [hunk 1]
```diff
@@ -57,9 +57,18 @@ const KNNClassifierDescription = """
...
     * `K::Int=5` : number of neighbors
     * `algorithm::Symbol = :kdtree` : one of `(:kdtree, :brutetree, :balltree)`
-    * `metric::Metric = Euclidean()` : a `Metric` object for the distance between points
-    * `leafsize::Int = 10` : at what number of points to stop splitting the tree
-    * `reorder::Bool = true` : if true puts points close in distance close in memory
+    * `metric::Metric = Euclidean()` : any `Metric` from 
+        [Distances.jl](https://github.com/JuliaStats/Distances.jl) for the 
+        distance between points. For `algorithm = :kdtree` only metrics which are of 
+        type `$(NN.MinkowskiMetric)` are supported.
+    * `leafsize::Int = algorithm == :brutetree ? 0 : 10` : determines the number of points
```
Comment (ablaom) [inline src/NearestNeighborModels.jl:64]: This way of writing the default is a little cryptic for the general user.  Maybe just write `leafsize::Int == 10` and just say this is ignored if  `algorithm=:brutetree`.

File: src/NearestNeighborModels.jl [hunk 2]
```diff
@@ -57,9 +57,18 @@ const KNNClassifierDescription = """
...
-    * `leafsize::Int = 10` : at what number of points to stop splitting the tree
-    * `reorder::Bool = true` : if true puts points close in distance close in memory
+    * `metric::Metric = Euclidean()` : any `Metric` from 
+        [Distances.jl](https://github.com/JuliaStats/Distances.jl) for the 
+        distance between points. For `algorithm = :kdtree` only metrics which are of 
+        type `$(NN.MinkowskiMetric)` are supported.
+    * `leafsize::Int = algorithm == :brutetree ? 0 : 10` : determines the number of points 
+        at which to stop splitting the tree. This option doesn't apply to `:brutetree` 
+        algorithm, since `brutetree` isn't actually a tree.
+    * `reorder::Bool = algorithm != :brutetree` : if `true` then points which are close in
```
Comment (ablaom) [inline src/NearestNeighborModels.jl:67]: Similarly here.

File: src/models.jl [hunk 3]
```diff
@@ -321,8 +321,90 @@ function MMI.predict(m::MultitargetKNNRegressor, fitresult, X)
...
+        end
+    end
+    if model.algorithm == :kdtree && !isa(model.metric, NN.MinkowskiMetric)
+        warning *= "For `algorithm = :kdtree` only metrics which are of type" * 
+        "`$(NN.MinkowskiMetric)` are supported.\nResetting `metric = Euclidean()`.\n"
+        model.metric = Euclidean()
+    end
+    return warning
+end
+
```
Comment (ablaom) [inline src/models.jl:405]: Nice, this all looks very thorough.

File: test/models.jl [hunk 4]
```diff
@@ -127,7 +192,7 @@ end
     end
 
     f, _, _ = MLJBase.fit(model, 1, X, y, w)
-    posterior3 = average([predict(model, f, X)...])
+    posterior3 = mean([predict(model, f, X)...])
```
Comment (ablaom) [inline test/models.jl:195]: Yes, I think `average` is now gone.

**Review by ablaom — APPROVED** [review]
Just the minor comments on the doc-strings.

Very thorough refactoring of the default constructor, thanks.

Please merge, make a release PR onto `master`, and tag a new release at your leisure.
